apiVersion: v1
kind: ConfigMap
metadata:
  name: nifi-config
  labels:
    app: nifi-config
data:
  NIFI_WEB_HTTP_HOST: "0.0.0.0"
  NIFI_WEB_HTTP_PORT: "9080"
  NIFI_JVM_HEAP_INIT: "512m"
  NIFI_JVM_HEAP_MAX: "512m"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nifi-app
  labels:
    app: nifi-server
spec:
  serviceName: nifi-service
  selector:
    matchLabels:
      app: nifi-server
  template:
    metadata:
      labels:
        app: nifi-server
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: nifi-app
          image: apache/nifi:1.12.1
          ports:
          - containerPort: 9080
          envFrom:
          - configMapRef:
              name: nifi-config
          volumeMounts:
            - name: nifi-flow-file
              mountPath: /opt/nifi/nifi-current/data/
            - name: nifi-properties-file
              mountPath: /opt/nifi/nifi-current/kubeconfig
          lifecycle:
            postStart:
              exec:
                command:
                  - bash
                  - -c
                  - |
                    cp -a /opt/nifi/nifi-current/kubeconfig/. /opt/nifi/nifi-current/conf
      volumes:
      - name: nifi-properties-file
        configMap:
          defaultMode: 0777
          name: nifi-properties
      - name: nifi-flow-file
        persistentVolumeClaim:
          claimName: nifi-azure-managed-default-disk
---
apiVersion: v1
kind: Service
metadata:
  name: nifi-service
  labels:
    app: nifi-service
spec:
  selector:
    app: nifi-server
  ports:
    - protocol: TCP
      name: http
      port: 9080
      targetPort: 9080
      
  ##Reference - https://stackoverflow.com/questions/51786114/changing-configuration-in-running-kubernetes-pod
